# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    build_app()
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_API_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_API_KEY'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    increment_build_number(
      build_number: ENV['BUILD_NUMBER'],
      xcodeproj: './Django Files.xcodeproj/project.pbxproj'
    )
    pilot
    upload_to_testflight(skip_waiting_for_build_processing: true, username: ENV['APPLE_ID'])
  end
end