devices([
  "iPhone 17 Pro Max",
  "iPhone 17",
  "iPad Pro 11-inch (M5)"
])

languages(["en-US"])

ios_version("latest")

scheme("Django Files")

clear_previous_screenshots(true)

override_status_bar(true)

concurrent_simulators(false)
