name: build-ios-app
on:
  push:
    branches:
      - 'master'
      - 'fastlane'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "Add SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v4
      - run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_URL: ${{ env.MATCH_URL }}
          CI: false