name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: selfhosted-macos-15
    steps:
      - name: "Debug"
        run: |
          fastlane env
          /usr/bin/xcodebuild -version
      - name: "Add SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v4
      - run: fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_URL: git@github.com:django-files/ios-match-certs.git
          CI: false
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
          ASC_API_ID: ${{ secrets.ASC_API_ID }}
          BUILD_NUMBER: ${{ github.run_number }}
