name: "Publish App Store"

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ !github.event.release.prerelease }}
    runs-on: ["macos-15"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set Run Number"
        id: run
        run: |
          echo "number=$(echo $((50 + ${{ github.run_number }})))" >> "$GITHUB_OUTPUT"

      - name: "Debug Run Number"
        continue-on-error: true
        run: |
          echo "run_number: ${{ steps.run.outputs.number }}"

      - name: "Add SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: "Publish App"
        run: fastlane ${{ github.event.release.prerelease && 'beta' || 'push_appstore' }}
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_URL: git@github.com:django-files/ios-match-certs.git
          CI: false
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
          ASC_API_ID: ${{ secrets.ASC_API_ID }}
          BUILD_NUMBER: ${{ steps.run.outputs.number }}
          VERSION_NUMBER: ${{ github.event.release.tag_name }}