name: "Publish"

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  command: ${{ github.event.release.prerelease && 'beta' || 'push_appstore' }}

jobs:
  publish:
    name: "Publish"
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set Run Number"
        id: run
        run: |
          echo "number=$(echo $((50 + ${{ github.run_number }})))" >> "$GITHUB_OUTPUT"

      - name: "Debug Run Number"
        continue-on-error: true
        run: |
          echo "number: ${{ steps.run.outputs.number }}"

      - name: "Add SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: "Google Services File"
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > "Django Files/GoogleService-Info.plist"

      - name: "Install iOS 18.0 Platform"
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          sudo xcodebuild -downloadPlatform iOS
          sudo xcodebuild -downloadPlatform iOS -platform iOS -version 18.0

      - name: "Fastlane ${{ env.command }}"
        run: fastlane ${{ env.command }}
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_URL: git@github.com:django-files/ios-match-certs.git
          CI: false
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY: ${{ secrets.ASC_API_KEY }}
          ASC_API_ID: ${{ secrets.ASC_API_ID }}
          BUILD_NUMBER: ${{ steps.run.outputs.number }}
          VERSION_NUMBER: ${{ github.event.release.tag_name }}

      - name: "Debug Fastlane"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: |
          ls -lAh .
          ls -lAh fastlane/metadata
          ls -lAh fastlane/screenshots

      - name: "Upload Metadata"
        if: ${{ !github.event.act }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_owner }}-metadata
          path: "fastlane/metadata"

      - name: "Upload Screenshots"
        if: ${{ !github.event.act }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_owner }}-screenshots
          path: "fastlane/screenshots"

      - name: "Upload IPA"
        if: ${{ !github.event.act }}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_owner }}-${{ env.command }}
          path: "Django Files.ipa"

      - name: "Upload IPA to Release"
        if: ${{ github.event_name == 'release' }}
        continue-on-error: true
        uses: svenstaro/upload-release-action@v2
        with:
          file: "Django Files.ipa"
          tag: ${{ github.ref }}
          overwrite: true

      - name: "Update Release Notes Action"
        if: ${{ github.event_name == 'release' }}
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          type: generic

      - name: "Send Failure Notification"
        if: ${{ failure() && github.event_name == 'release' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
