name: "Django Files iOS CI"
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: "Tests"
    runs-on: ['self-hosted', 'macOS', 'ARM64'] 
    steps:
      - name: "Add Match Repo SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: actions/checkout@v4
      - name: "Fastlane Tests"
        run: fastlane tests
        env:
          CI: true
