name: "CI"

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/tests.yml"
      - "Django Files/**"
      - "Django Files*/**"
      - "Gemfile"
      - "Gemfile.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: "Tests"
    runs-on: ["macos-15"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Add Match Repo SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: "Google Services File"
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > "Django Files/GoogleService-Info.plist"

      - name: "List Installed iOS Platforms"
        run: |
          echo "=== Currently Installed iOS Platforms ==="
          xcodebuild -showsdks | grep iOS || echo "No iOS SDKs found"
          echo ""
          echo "=== Xcode Version ==="
          xcodebuild -version
          echo ""
          echo "=== Available Platforms ==="
          xcodebuild -list -project "Django Files.xcodeproj" | grep -A 10 "Available platforms:" || echo "Could not list project platforms"

      - name: "Install iOS 18.0 Platform"
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          sudo xcodebuild -downloadPlatform iOS
          sudo xcodebuild -downloadPlatform iOS -platform iOS -version 18.0

      - name: "Fastlane Tests"
        run: fastlane tests
        env:
          CI: true
