name: "CI"

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/tests.yml"
      - "Django Files/**"
      - "Django Files*/**"
      - "Gemfile"
      - "Gemfile.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: "Tests"
    runs-on: ["macos-15"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Add Match Repo SSH Key"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: "Google Services File"
        run: |
          echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > "Django Files/GoogleService-Info.plist"

      - name: "Fastlane Tests"
        run: fastlane tests
        env:
          CI: true
